version: '3.8'
services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      SYMFONY_ENV: dev

  webserver:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: