services:
  backend:
    build:
      context: ./backend
    container_name: symfony-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200" # Pour mode dev
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdd
      MYSQL_USER: ines
      MYSQL_PASSWORD: azertyines..
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
